### ISSUE TITLE
Plugin not working on 1.16 and 1.17

### ISSUE THREAD

**Issue by xar55** [Syrent/SayanVanish#197] opened 2023-07-03 02:03 UTC
### Server backend version

Purpur 1.16.5 build 1171

### Server Velocity version

Velocity 3.2.0-SNAPSHOT build 259

### VelocityVanish version

3.19.1-beta.10

### Describe the bug

plugin not working (using java 11):

Could not load 'plugins/VelocityVanish-3.19.0.jar' in folder 'plugins'                                                                                                                                    
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: ir/syrent/velocityvanish/spigot/VelocityVanishSpigot has been compiled by a more recent version of the Java Runtime (class file version 61.0), this versio
n of the Java Runtime only recognizes class file versions up to 55.0                                                                                                                                                                        
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                              
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                             
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                            
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                              
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                                       at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                                         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                         
        at java.lang.Thread.run(Thread.java:829) [?:?]                                                                
Caused by: java.lang.UnsupportedClassVersionError: ir/syrent/velocityvanish/spigot/VelocityVanishSpigot has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only reco
gnizes class file versions up to 55.0                      
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]                                                   
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]                                            
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]                             
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                             
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]                                               
luginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]                                                      
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                             
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]                                               
        at java.lang.Class.forName0(Native Method) ~[?:?]                                                             
        at java.lang.Class.forName(Class.java:398) ~[?:?]                                                             
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                                 
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Purpur-1171]                                                                                                              
        ... 7 more

### Expected behavior

plugin working

### Steps to reproduce

1. use same server versions as me

### Additional info

also tried older plugin versions but no luck

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment] 2023-07-03 07:47
Duplicate #40
Unfortunately, with the current plugin codebase, I can't fix it right now.
I'll try to fix it in future updates

**Comment by SladeHazard** [comment] 2023-09-28 00:33
> Duplicate #40 Unfortunately, with the current plugin codebase, I can't fix it right now. I'll try to fix it in future updates

any update on this? I can't use it either, java 11, 1.12.2

**Comment by Syrent** [comment] 2023-09-28 17:38
> > Duplicate #40 Unfortunately, with the current plugin codebase, I can't fix it right now. I'll try to fix it in future updates
> 
> any update on this? I can't use it either, java 11, 1.12.2

Hello, the issue is unrelated to Java 11. VelocityVanish simply does not support versions 1.16 and 1.17. If you wish to use it with 1.12.2, you can do so without any difficulties. However, you will need to use the latest Java LTS (version 17). As far as I know, Java 17 also functions perfectly fine with version 1.12.2.

**Comment by SladeHazard** [comment] 2023-09-28 18:43
> > > Duplicate #40 Unfortunately, with the current plugin codebase, I can't fix it right now. I'll try to fix it in future updates
> > 
> > 
> > any update on this? I can't use it either, java 11, 1.12.2
> 
> Hello, this issue is unrelated to Java 11. VelocityVanish simply does not support versions 1.16 and 1.17. If you wish to use it with 1.12.2, you can do so without any difficulties. However, you will need to use the latest Java LTS (version 17). As far as I know, Java 17 also functions perfectly fine with version 1.12.2.

well java 17 does function perfectly fine with 1.12.2 however, most of the popular plugins do not work correctly with anything above java 11 on 1.12.2

**Comment by Syrent** [comment] 2023-09-28 20:56
> > > > Duplicate #40 Unfortunately, with the current plugin codebase, I can't fix it right now. I'll try to fix it in future updates
> > > 
> > > 
> > > any update on this? I can't use it either, java 11, 1.12.2
> > 
> > 
> > Hello, this issue is unrelated to Java 11. VelocityVanish simply does not support versions 1.16 and 1.17. If you wish to use it with 1.12.2, you can do so without any difficulties. However, you will need to use the latest Java LTS (version 17). As far as I know, Java 17 also functions perfectly fine with version 1.12.2.
> 
> well java 17 does function perfectly fine with 1.12.2 however, most of the popular plugins do not work correctly with anything above java 11 on 1.12.2

I'm unable to compile the plugin with legacy Java versions. Compiling the plugin using legacy API/Java would necessitate sacrificing certain features and significantly extending the development timeline for implementable features. My primary focus is on modern implementations and APIs, and I am considering the possibility of removing support for legacy versions in the future. For full legacy support, I recommend considering alternatives such as SuperVanish or PremiumVanish.

**Comment by Syrent** [comment] 2024-05-31 10:59
Fixed in new version

**Closed by Syrent** 2024-05-31 10:59 UTC
Labels: bug, wontfix
